# Generated by Django 5.1.5 on 2025-01-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Account'}, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance_tracker.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Expense'}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type__in': ['Income', 'Expense', 'Investment']}, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='finance_tracker.account'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Income'}, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Investment'}, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type__in': ['Income', 'Expense']}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='finance_tracker.category'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
    ]
