# Generated by Django 5.1.5 on 2025-01-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_initial'),
        ('finance_tracker', '0003_auto_20250127_1116'),
    ]

    operations = [
    ]
